Bugfix: response header notreflecting correct version of http #1689
wiremock/wiremock pull request #1890
Opened 2022-06-02 11:13 UTC by SaiPoojithaDubba

link to the issue: #1689

2022-06-02 11:24 UTC, tomakehurst requested changes
This is a good start and I think only one change is needed, which is to move `Response.setProtocol()` to `Response.Builder.protocol()` so that `Response` remains immutable.

2022-06-02 16:54 UTC, SaiPoojithaDubba commented
> This is a good start and I think only one change is needed, which is to move `Response.setProtocol()` to `Response.Builder.protocol()` so that `Response` remains immutable.

Change committed!

2022-06-06 11:25 UTC, tomakehurst approved these changes

2022-06-06 11:25 UTC, merged

2022-06-06 11:25 UTC, tomakehurst commented
Thanks!