Proposal. Replacing com.google.common.base.MoreObjects.firstNonNull &…
wiremock/wiremock pull request #2228
Opened 2023-06-19 06:05 UTC by pks-1981

Proposal. Replacing com.google.common.base.MoreObjects.firstNonNull & com.google.common.base.Preconditions.checkArgument

## References

https://github.com/wiremock/wiremock/issues/2111

## Submitter checklist

- [ ] The PR request is well described and justified, including the body and the references
- [ ] The PR title represents the desired changelog entry
- [ ] The repository's code style is followed (see the contributing guide)
- [ ] Test coverage that demonstrates that the change works as expected
- [ ] For new features, there's necessary documentation in this pull request or in a subsequent PR to [wiremock.org](https://github.com/wiremock/wiremock.org)

2023-07-04 11:20 UTC, oleg-nenashev requested changes
Requesting changes because of API changes that do not seem to be related to the PRs purpose, or justified otherwise. Let's do them separately at least. There is also a bunch of other refactorings, but I do not mind

2023-07-04 11:20 UTC, oleg-nenashev commented on src/main/java/com/github/tomakehurst/wiremock/stubbing/AbstractScenarios.java
> +  protected AbstractScenarios(ScenariosStore store) {
Revert? Seems to be a legit API

2023-07-04 11:20 UTC, oleg-nenashev commented on src/main/java/com/github/tomakehurst/wiremock/stubbing/AbstractStubMappings.java
> +  protected AbstractStubMappings(
Legit API?

2023-07-05 05:53 UTC, pks-1981 commented
@oleg-nenashev 
Hello
I don't understand...
I did everything, but it's like nothing...
![image](https://github.com/wiremock/wiremock/assets/33098392/1f973427-a1cd-478a-87fc-11bc1f114b83)

2023-07-05 09:37 UTC, merged

2023-07-06 08:33 UTC, oleg-nenashev commented
@pks-1981

> I don't understand...
I did everything, but it's like nothing...

Is it still actual?